"""Add import_logs table

Revision ID: 35e68ecb561a
Revises: c1bcada7c249
Create Date: 2025-12-19 09:37:10.149670

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '35e68ecb561a'
down_revision: Union[str, Sequence[str], None] = 'c1bcada7c249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
